# Used by "mix format".
#
# `spark_locals_without_parens` is generated by
# `mix spark.formatter --extensions AshMetrics`; do not edit it by hand.
spark_locals_without_parens = [
  counter: 1,
  counter: 2,
  description: 1,
  name: 1,
  outcomes: 1,
  tags: 1
]

[
  import_deps: [:ash, :spark],
  plugins: [Spark.Formatter],
  inputs: ["{mix,.formatter,.credo}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  locals_without_parens: spark_locals_without_parens,
  export: [locals_without_parens: spark_locals_without_parens]
]
