defmodule AshMetrics.Info do
  @moduledoc """
  Introspection of the `metrics` section of a resource.

  In addition to the accessors generated by `Spark.InfoGenerator`
  (`metrics/1`, `metrics_options/1`, `metrics_name/1`, `metrics_name!/1`) this
  module provides the lookups the rest of the package uses: `metric/2`,
  `metric!/2` and `name/1`.
  """

  use Spark.InfoGenerator, extension: AshMetrics, sections: [:metrics]

  alias Ash.Resource.Info, as: ResourceInfo
  alias AshMetrics.Dsl.Counter
  alias AshMetrics.Dsl.Distribution

  @typedoc "Any metric declaration that can appear in a `metrics` block."
  @type metric :: Counter.t() | Distribution.t()

  @typedoc "A resource, or the DSL state of a resource being compiled."
  @type resource :: module() | Spark.Dsl.t()

  @doc """
  Fetches a single metric declaration by name.

  Returns `{:ok, metric}` or `:error`. See `metric!/2` for the raising variant.
  """
  @spec metric(resource(), atom()) :: {:ok, metric()} | :error
  def metric(resource, name) do
    case Enum.find(metrics(resource), &(&1.name == name)) do
      nil -> :error
      metric -> {:ok, metric}
    end
  end

  @doc """
  Fetches a single metric declaration by name, raising if it is not declared.

  The `ArgumentError` lists the metrics the resource does declare, since the
  usual cause is a typo at an `AshMetrics.increment/3` or `AshMetrics.observe/4`
  call site.
  """
  @spec metric!(resource(), atom()) :: metric()
  def metric!(resource, name) do
    case metric(resource, name) do
      {:ok, metric} ->
        metric

      :error ->
        raise ArgumentError,
              "no metric #{inspect(name)} is declared on #{inspect(resource)}. " <>
                "Declared metrics: #{available(resource)}"
    end
  end

  @doc """
  The name segment used for a resource in its metric names.

  This is the `name` option of the `metrics` section when set, and
  `Ash.Resource.Info.short_name/1` otherwise.
  """
  @spec name(resource()) :: atom()
  def name(resource) do
    case metrics_name(resource) do
      {:ok, name} when not is_nil(name) -> name
      _otherwise -> ResourceInfo.short_name(resource)
    end
  end

  @spec available(resource()) :: String.t()
  defp available(resource) do
    case Enum.map(metrics(resource), & &1.name) do
      [] -> "none"
      names -> Enum.map_join(names, ", ", &inspect/1)
    end
  end
end
