defmodule AshMetrics.Test.Repo.Migrations.AddPgTickets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pg_tickets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text)
      add(:priority, :text)
      add(:assignee, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:resolved_at, :utc_datetime_usec)
    end
  end

  def down do
    drop(table(:pg_tickets))
  end
end
