defmodule AshMetrics.Test.Repo.Migrations.AddPgTasksQueuedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pg_tasks) do
      add(:queued_at, :naive_datetime)
    end
  end

  def down do
    alter table(:pg_tasks) do
      remove(:queued_at)
    end
  end
end
