defmodule AshMetrics.Test.Repo.Migrations.AddPgJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pg_jobs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text)
      add(:provider, :text)
    end
  end

  def down do
    drop(table(:pg_jobs))
  end
end
