defmodule AshMetrics.Test.Repo.Migrations.AddPgTicketComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pg_ticket_comments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :ticket_id,
        references(:pg_tickets,
          column: :id,
          name: "pg_ticket_comments_ticket_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:pg_ticket_comments, "pg_ticket_comments_ticket_id_fkey"))

    drop(table(:pg_ticket_comments))
  end
end
