defmodule AshMetrics.Test.Repo.Migrations.AddPgTaskVariants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pg_limited_tasks, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    execute("CREATE SCHEMA IF NOT EXISTS ash_metrics_prefixed")

    create table(:pg_prefixed_tasks, primary_key: false, prefix: "ash_metrics_prefixed") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:pg_task_notes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :task_id,
        references(:pg_tasks,
          column: :id,
          name: "pg_task_notes_task_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:pg_task_notes, "pg_task_notes_task_id_fkey"))

    drop(table(:pg_task_notes))

    drop(table(:pg_prefixed_tasks, prefix: "ash_metrics_prefixed"))

    drop(table(:pg_limited_tasks))
  end
end
